# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |config|

  config.vm.define "source" do |source|
    # source.vm.box = "ubuntu/jammy64"
    source.vm.box = "ubuntu/bionic64"
    source.vm.synced_folder "src/", "/home/vagrant/src"                
    source.vm.network :private_network, ip: "192.168.56.101"
    source.vm.network "forwarded_port", guest: 8080, host: 80

    source.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
      vb.name = "source"
    end

    source.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/America/New_York /etc/localtime", run: "always"
  end

  config.vm.define "sink" do |sink|
    sink.vm.box = "ubuntu/bionic64"
    sink.vm.synced_folder "src/", "/home/vagrant/src"                
    sink.vm.network :private_network, ip: "192.168.56.102"
    sink.vm.network "forwarded_port", guest: 9000, host: 9000

    sink.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = "4"
      vb.name = "sink"
    end

    # Add Google Chrome repository
    sink.vm.provision :shell, inline: "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub|sudo apt-key add -"
    sink.vm.provision :shell, inline: "sudo sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" > /etc/apt/sources.list.d/google.list'"

    # Update repositories
    sink.vm.provision :shell, inline: "sudo apt-get update -y"

    # Upgrade installed packages
    sink.vm.provision :shell, inline: "sudo apt-get upgrade -y"

    # Add desktop environment
    sink.vm.provision :shell, inline: "sudo apt-get install -y --no-install-recommends ubuntu-desktop"
    sink.vm.provision :shell, inline: "sudo apt-get install -y --no-install-recommends virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11"

    # Add `vagrant` to Administrator
    sink.vm.provision :shell, inline: "sudo usermod -a -G sudo vagrant"

    # Add Google Chrome
    sink.vm.provision :shell, inline: "sudo apt-get install -y google-chrome-stable"

    # Restart
    sink.vm.provision :shell, inline: "sudo shutdown -r now"

    # sync clock
    sink.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/America/New_York /etc/localtime", run: "always"

    # Bootstrap for development, then remove the devconfig sources
    config.vm.provision "shell", inline: "rm -rf /tmp/devconfig", privileged: false
    config.vm.provision "shell", inline: "git clone https://github.com/zachwaite/devconfig /tmp/devconfig", privileged: false
    config.vm.provision "shell", inline: "DEVCONFIG_ROOT=/tmp/devconfig /tmp/devconfig/bin/provision-neovim", privileged: false
    config.vm.provision "shell", inline: "sed -i 's/zach/vagrant/g' /home/vagrant/.vimrc", privileged: false, run: "always"
    config.vm.provision "shell", inline: "sed -i 's/zach/vagrant/g' /home/vagrant/.bashrc", privileged: false, run: "always"
  end


end
